sudo: required
language: cpp
dist: trusty
compiler: g++
install: export CXX="g++-5"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5

before_install: 
  - sudo apt-get update -qq
  - mkdir M2DO_FEA/bin 
  - mkdir M2DO_LSM/bin
  - mkdir projects/compliance_minimization/bin
  - mkdir projects/compliance_minimization/results

script: 
  - cd projects/compliance_minimization
  - make 

after_success:
  - ./bin/a.out > log.txt
  - cat log.txt | tail